parameters: {}
environment: {}
packages:
    - name: openai
      shared: false
      functions:
        - name: summarize
          binary: false
          runtime: python:default
          web: true
          webSecure: false
          environment: 
            OPENAI_API_KEY: "${OPENAI_API_KEY}"
    - name: slack
      shared: false
      functions:
        - name: get_urls
          binary: false
          runtime: python:default
          web: true
          webSecure: false
          environment: 
            SLACK_TOKEN: "${SLACK_TOKEN}"
        - name: post_podcast
          binary: false
          runtime: python:default
          web: true
          webSecure: false
          environment: 
            SLACK_TOKEN: "${SLACK_TOKEN}"
    - name: text
      shared: false
      functions:
        - name: split
          binary: false
          runtime: python:default
          web: true
          webSecure: false     
  
