version: '3.7'
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://164.90.183.32:5678/
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - N8N_USER_MANAGEMENT_DISABLED=true
    volumes:
      - /root/n8n:/home/node/.n8n
  openai_summarize:
    image: openai_summarize
    restart: always
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
